site_name: PyRevolut
site_description: "PyRevolut is a Python wrapper for the Revolut Business API."
site_author: "Trevor Visser"
docs_dir: docs/
repo_name: "Trevypants/pyrevolut"
repo_url: "https://github.com/Trevypants/pyrevolut"
nav:
  - Home: index.md
  - About: about.md
theme: 
  name: material