name: Upload Python Package to PyPI

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    strategy:
      matrix:
        python-version: [3.11]
    defaults:
      run:
        shell: bash
    environment: ${{ github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #   ----------- check-out repo  ------------
      #----------------------------------------------
      - uses: actions/checkout@v4

      #----------------------------------------------
      #   ------------  setup python  -----------
      #----------------------------------------------
      - name: 🔧 Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: 📜 Install Poetry
        run: |
          python -m pip install -U pip poetry
          poetry --version

      #----------------------------------
      #  -----  load cached venv  -----
      #----------------------------------
      - name: Load cached venv
        id: cached-pip-wheels
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      #   ------------  install deps  ------------
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry install --no-interaction

      #------------------------------------------------
      #   ------------  build and publish  ------------
      #------------------------------------------------
      - name: Build and publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: make publish-pypi
